spring:
  datasource:
    url: jdbc:mysql://194.163.46.5:3306/u896018919_library_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: u896018919_root
    password: EnterpriseAppDevelopment@1
  jpa:
    hibernate:
      ddl-auto: validate   # keep schema as source-of-truth via Flyway
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration  # default, but explicit is fine

logging:
  level:
    org.hibernate.SQL: warn


